name: "HCL AppScan DAST - recordedLogin"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ASoC DAST Scan
        uses: HCL-TECH-SOFTWARE/appscan-dast-action@main
        with:
          scan_name: Check_DAST_Self_Host_Runner
          baseurl:  https://staging.appscan.internal
          acceptssl: true
          asoc_key: ${{secrets.STAGE_SAST_KEY}}
          asoc_secret: ${{secrets.STAGE_SAST_SECRET}}
          application_id: c97004ac-f856-45bd-acca-3780c5f4ba9d
          dynamic_scan_type: dast
          starting_URL: 'https://demo.testfire.net'
          login_method: recorded
          network: public
          login_sequence_file: './loginRecord/DTF_Login_NewHTTPS.dast.config'
          fail_for_noncompliance: false
          wait_for_analysis: true
      - uses: actions/upload-artifact@v4
        name: Upload HCL AppScan HTML Report to Github Artifacts
        with:
          name: AppScan Security Scan HTML Report 
          path: '**/AppScan*.html'
        if: success() || failure()
