name: "HCL AppScan DAST - userPass"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run ASoC DAST Scan
        uses: HCL-TECH-SOFTWARE/appscan-dast-action@main
        with:
          baseurl:  https://staging.appscan.internal
          acceptssl: true
          asoc_key: ${{secrets.STAGE_SAST_KEY}}
          asoc_secret: ${{secrets.STAGE_SAST_SECRET}}
          application_id: c97004ac-f856-45bd-acca-3780c5f4ba9d
          dynamic_scan_type: dast
          starting_URL: 'https://demo.testfire.net'
          login_method: userpass
          login_user: jsmith
          login_password: demo1234
          network: public
          fail_for_noncompliance: false
          wait_for_analysis: true
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.6.1
        name: Upload HCL AppScan HTML Report to Github Artifacts
        with:
          name: AppScan Security Scan HTML Report 
          path: '**/AppScan*.html'
        if: success() || failure()
